[General]
    default_prefix = "m/"

[Exchange]
    api_root = "http://localhost:8082"
    webserver_root = "http://localhost:5000"

[Database]
    minsize = 1
    charset = "utf8mb4"
    echo = true
    autocommit = true
